In [1]:
import numpy as np


In [3]:
x=np.array([154,139,154,192,180,140,154,155,192])
x

array([154, 139, 154, 192, 180, 140, 154, 155, 192])

# Sum

In [4]:
np.sum(x)

1460

# Mean

In [7]:
#option-1

m=np.sum(x)/len(x)
m





162.22222222222223

In [8]:
#option-2 
np.mean(x)


162.22222222222223

In [9]:
#option -3

x.mean()

162.22222222222223

# Mode

In [10]:
from scipy.stats import mode
mode(x)

C:\Users\Admin\AppData\Local\Temp\ipykernel_5852\2992914129.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode(x)


ModeResult(mode=array([154]), count=array([3]))

# Minimum 

In [11]:
np.min(x)

139

# Maximum

In [12]:
np.max(x)

192

In [13]:
x.min()
x.max()

192

# Range

In [14]:
x.max()-x.min()

53

# Mean absolute Deviation

In [15]:
x=np.array([5,9,16,17,18])
x

array([ 5,  9, 16, 17, 18])

In [18]:
deviation=x-x.mean()
deviation

array([-8., -4.,  3.,  4.,  5.])

In [19]:
abs_deviation=abs(deviation)
abs_deviation

array([8., 4., 3., 4., 5.])

In [20]:
np.mean(abs_deviation)

4.8

# Mean Square Deviation

In [21]:
x=np.array([5,9,16,17,18])
deviation=x-x.mean()
sqr_deviation=deviation*deviation

np.mean(sqr_deviation)

26.0

# Variance/Mean square deviation

In [22]:
np.var(x)

26.0

* Default population Variance

# Standard deviation

In [24]:
#option -1

var=np.var(x)
std=np.sqrt(var)
std

5.0990195135927845

In [25]:
#option 2

np.std(x)

5.0990195135927845

# Sample Variance & Sample Standard Deviation

In [26]:
s=np.array([1298,1844,1539,1311])

In [27]:
sample_variance=np.var(s)*len(s)/(len(s)-1)
sample_variance

65455.333333333336

In [28]:
sample_std_dev=np.sqrt(sample_variance)
sample_std_dev

255.8423994050504

# Percentile

In [29]:
ages=[5,31,43,48,50,41,7,11,15,39,90,82,32,2,8,6,25,36,27,61,31]

In [30]:
np.percentile(ages,25)

11.0

In [31]:
np.percentile(ages,75)

43.0

In [32]:
np.percentile(ages,[25,50,75])

array([11., 31., 43.])