# Numpy

In [1]:
lst=[1,2,3,4]
print(lst)
type(lst)

[1, 2, 3, 4]


list

Numpy(Numerical python)


In [4]:
import numpy as np  #import library

In [5]:
np.__version__  #to check version of numpy.

'1.24.3'

Ndarray

The ndarray is created using an array function in Numpy.

   numpy.array(object)

In [6]:
a=[1,2,3,4,5]

np_a = np.array(a)
print(np_a)
type(np_a)

[1 2 3 4 5]


numpy.ndarray

In [7]:
np_a   

array([1, 2, 3, 4, 5])

# Creating Numpy Arrays
 
 0-D

In [9]:
arr=np.array(45)
print(arr)
type(arr)

45


numpy.ndarray

1-D

In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
a = np.array((2,3,4,5,6))
print(a)

[2 3 4 5 6]


In [14]:
#Print array Dimension

a.ndim

1

In [15]:
#print Shape of array

a.shape

(5,)

# Functions for creating arrays

In [16]:
a = np.arange(10,101,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [18]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
 np.ones(3)

array([1., 1., 1.])

In [26]:
np.random.randint(1,100,5)

array([40, 65, 12, 76, 75])

# Acessessing Elements

In [31]:
a = np.arange(1,20,2)
print(a)
a[5]

[ 1  3  5  7  9 11 13 15 17 19]


11

In [32]:
a[1:8:2]

array([ 3,  7, 11, 15])

In [34]:
a[[0,1,3,4,5]]

array([ 1,  3,  7,  9, 11])

In [35]:
4. Acessing a multiple values based on condition or Fancy Indexing.


SyntaxError: invalid syntax (3954280239.py, line 1)

In [37]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
a[a%2==0]

array([], dtype=int32)

In [39]:
a[a>10]

array([11, 13, 15, 17, 19])

In [41]:
a[a==3]

array([3])

# Numpy is Mutable

In [42]:
1.Replace
2.Add
3.Remove

SyntaxError: invalid decimal literal (2968637551.py, line 1)

In [44]:
#Replacing single value in array.

a[5]=200
print(a)

[  1   3   5   7   9 200  13  15  17  19]


In [46]:
#Replacing a multiple values in aarray.

a[[1,5]]=80
print(a)

[ 1 80  5  7  9 80 13 15 17 19]


In [48]:
#Add value in array

b=np.append(a,[110,200])
print(b)

[  1  80   5   7   9  80  13  15  17  19 110 200]


In [49]:
#Delete a single value in array

b=np.delete(a,8)
print("Numpy array after deleton of one element:",a)

Numpy array after deleton of one element: [ 1 80  5  7  9 80 13 15 17 19]


In [51]:
#Delete multiple values in array.

b=np.delete(a,[1,4,5])
print(b)

[ 1  5  7 13 15 17 19]


# Sort

In [52]:
np.sort([4,5,6,8,3,8,9]) #bydefault ascending order.

array([3, 4, 5, 6, 8, 8, 9])

In [53]:
np.sort([3,7,8,9,5,4,2])[::-1] #desending order.

array([9, 8, 7, 5, 4, 3, 2])

# copy array

In [54]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [55]:
arr=np.array([1.234,4.555,6.555])
np.around(arr)

array([1., 5., 7.])

In [56]:
np.around(arr,2)

array([1.23, 4.56, 6.56])

# Operations

In [58]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [59]:
a+1

array([2, 3, 4, 5, 6])

In [60]:
a**2

array([ 1,  4,  9, 16, 25])

In [62]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
c=np.array([39,8,7,9])
print(a,b,c)

[1 2 3 4] [4 5 6 7] [39  8  7  9]


In [63]:
a+b

array([ 5,  7,  9, 11])

In [64]:
a-b

array([-3, -3, -3, -3])

In [65]:
a*b

array([ 4, 10, 18, 28])

In [66]:
a==b

array([False, False, False, False])

In [67]:
a>b

array([False, False, False, False])

In [68]:
a<b

array([ True,  True,  True,  True])

In [69]:
np.array_equal(a,b)

False

In [70]:
np.array_equal(a,c)

False

In [86]:
a=np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [87]:
np.sin(a)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021])

In [88]:
np.cos(a)

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026,
        0.0044257 ])

In [89]:
np.log(a)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527])

In [90]:
np.exp(a)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04])

# Statistical operations

In [91]:
np.mean(a)

6.0

In [92]:
np.median(a)

6.0

In [95]:
np.std(a)

3.415650255319866

# 2D Numpy Arraya

In [97]:
b=np.array([[1,2,3,4],[5,6,7,7]])
print(b)

[[1 2 3 4]
 [5 6 7 7]]


In [98]:
b.ndim

2

In [99]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [104]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [105]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [109]:
a=np.array([[10,20,30],[30,40,50]])
print(a)
print(a[1,1])

[[10 20 30]
 [30 40 50]]
40


In [110]:
a[1,1]

40

In [111]:
a[0,1]

20

In [112]:
#Assigning value in 2d array
a[1,1]=25
a

array([[10, 20, 30],
       [30, 25, 50]])

Flattering: Converting nd array to 1-D array.


In [113]:
a=np.array([1,2,3,4,5])
a.ravel()

array([1, 2, 3, 4, 5])

Reshape array

In [117]:
a=np.arange(1,31)
print(a)

a.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


(30,)

In [119]:
a1=a.reshape(2,15)
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

Transpose Array

In [120]:
c=a.T
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [123]:
#Sorting along an axis=1-->row and axis-->column

a=np.array([[5,4,3],[2,5,8]])
print(a)
b=np.sort(a,axis=0)
print(b)

[[5 4 3]
 [2 5 8]]
[[2 4 3]
 [5 5 8]]


In [126]:
a=np.array([[1,2],[3,4],[5,6]])

b=np.array([[4,4],[4,4],[4,4]])

#adding two arrays
print(a+b)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [127]:
#Multiply arrays

print(a*b)

[[ 4  8]
 [12 16]
 [20 24]]


In [128]:
#Matrix Multiplication

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

np.matmul(a,b)

array([[19, 22],
       [43, 50]])